"""add_wheel_states_table

Revision ID: 2bc2d2ecdba1
Revises: 44f6a0edcdf5
Create Date: 2026-03-04 15:53:12.438731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bc2d2ecdba1'
down_revision: Union[str, Sequence[str], None] = '44f6a0edcdf5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wheel_states',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('original_cost', sa.Float(), nullable=False),
    sa.Column('total_premium_collected', sa.Float(), nullable=False),
    sa.Column('cycle_count', sa.Integer(), nullable=False),
    sa.Column('entered_state_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wheel_states_symbol'), 'wheel_states', ['symbol'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wheel_states_symbol'), table_name='wheel_states')
    op.drop_table('wheel_states')
    # ### end Alembic commands ###
