"""add asset_type to scanner_opportunities and journal_entries

Revision ID: 44f6a0edcdf5
Revises: 9fb3e5a8d5aa
Create Date: 2026-03-04 15:26:00.162433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44f6a0edcdf5'
down_revision: Union[str, Sequence[str], None] = '9fb3e5a8d5aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('journal_entries', sa.Column('asset_type', sa.String(), nullable=True))
    op.create_index(op.f('ix_journal_entries_asset_type'), 'journal_entries', ['asset_type'], unique=False)
    op.add_column('scanner_opportunities', sa.Column('asset_type', sa.String(), nullable=False))
    op.add_column('scanner_opportunities', sa.Column('avg_daily_volume', sa.Float(), nullable=True))
    op.create_index(op.f('ix_scanner_opportunities_asset_type'), 'scanner_opportunities', ['asset_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scanner_opportunities_asset_type'), table_name='scanner_opportunities')
    op.drop_column('scanner_opportunities', 'avg_daily_volume')
    op.drop_column('scanner_opportunities', 'asset_type')
    op.drop_index(op.f('ix_journal_entries_asset_type'), table_name='journal_entries')
    op.drop_column('journal_entries', 'asset_type')
    # ### end Alembic commands ###
