"""add_proposals_table

Revision ID: 5c460d2ff840
Revises: 2bc2d2ecdba1
Create Date: 2026-03-16 16:41:22.818828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c460d2ff840'
down_revision: Union[str, Sequence[str], None] = '2bc2d2ecdba1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proposals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('batch_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('agent_name', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('asset_type', sa.String(), nullable=False),
    sa.Column('contract_type', sa.String(), nullable=False),
    sa.Column('option_symbol', sa.String(), nullable=True),
    sa.Column('strike', sa.Float(), nullable=False),
    sa.Column('expiration', sa.String(), nullable=False),
    sa.Column('delta', sa.Float(), nullable=False),
    sa.Column('dte', sa.Integer(), nullable=False),
    sa.Column('bid', sa.Float(), nullable=False),
    sa.Column('ask', sa.Float(), nullable=False),
    sa.Column('mid_price', sa.Float(), nullable=False),
    sa.Column('premium_per_contract', sa.Float(), nullable=False),
    sa.Column('contracts', sa.Integer(), nullable=False),
    sa.Column('total_premium', sa.Float(), nullable=False),
    sa.Column('collateral_required', sa.Float(), nullable=False),
    sa.Column('annualized_return', sa.Float(), nullable=False),
    sa.Column('probability_of_profit', sa.Float(), nullable=False),
    sa.Column('max_risk', sa.Float(), nullable=False),
    sa.Column('distance_otm_pct', sa.Float(), nullable=False),
    sa.Column('iv_rank', sa.Float(), nullable=False),
    sa.Column('scanner_score', sa.Float(), nullable=True),
    sa.Column('rationale', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('executed_at', sa.DateTime(), nullable=True),
    sa.Column('rejected_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proposals_batch_id'), 'proposals', ['batch_id'], unique=False)
    op.create_index(op.f('ix_proposals_status'), 'proposals', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_proposals_status'), table_name='proposals')
    op.drop_index(op.f('ix_proposals_batch_id'), table_name='proposals')
    op.drop_table('proposals')
    # ### end Alembic commands ###
