"""Initial migration: all models

Revision ID: 9fb3e5a8d5aa
Revises: 
Create Date: 2026-03-04 14:40:42.307436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fb3e5a8d5aa'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_performance',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agent_name', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('total_trades', sa.Integer(), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.Column('losses', sa.Integer(), nullable=False),
    sa.Column('total_premium', sa.Float(), nullable=False),
    sa.Column('realized_pnl', sa.Float(), nullable=False),
    sa.Column('win_rate', sa.Float(), nullable=True),
    sa.Column('avg_return_per_trade', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_name', 'date', name='uq_agent_performance_date')
    )
    op.create_index(op.f('ix_agent_performance_agent_name'), 'agent_performance', ['agent_name'], unique=False)
    op.create_index(op.f('ix_agent_performance_date'), 'agent_performance', ['date'], unique=False)
    op.create_table('journal_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agent_name', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('option_symbol', sa.String(), nullable=True),
    sa.Column('contract_type', sa.String(), nullable=False),
    sa.Column('strike', sa.Float(), nullable=False),
    sa.Column('expiration', sa.String(), nullable=False),
    sa.Column('side', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('fill_price', sa.Float(), nullable=False),
    sa.Column('premium', sa.Float(), nullable=True),
    sa.Column('entry_iv_rank', sa.Float(), nullable=True),
    sa.Column('entry_stock_price', sa.Float(), nullable=True),
    sa.Column('entry_vix_level', sa.Float(), nullable=True),
    sa.Column('entry_distance_from_support', sa.Float(), nullable=True),
    sa.Column('entry_distance_from_20ma', sa.Float(), nullable=True),
    sa.Column('entry_distance_from_50ma', sa.Float(), nullable=True),
    sa.Column('entry_scanner_composite_score', sa.Float(), nullable=True),
    sa.Column('entry_sector', sa.String(), nullable=True),
    sa.Column('delta_at_entry', sa.Float(), nullable=True),
    sa.Column('dte_at_entry', sa.Integer(), nullable=True),
    sa.Column('annualized_return_at_entry', sa.Float(), nullable=True),
    sa.Column('probability_of_profit', sa.Float(), nullable=True),
    sa.Column('exit_stock_price', sa.Float(), nullable=True),
    sa.Column('exit_iv_rank', sa.Float(), nullable=True),
    sa.Column('exit_reason', sa.String(), nullable=True),
    sa.Column('realized_pnl', sa.Float(), nullable=True),
    sa.Column('days_held', sa.Integer(), nullable=True),
    sa.Column('return_pct', sa.Float(), nullable=True),
    sa.Column('entry_at', sa.DateTime(), nullable=False),
    sa.Column('exit_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_journal_entries_agent_name'), 'journal_entries', ['agent_name'], unique=False)
    op.create_index(op.f('ix_journal_entries_entry_at'), 'journal_entries', ['entry_at'], unique=False)
    op.create_index(op.f('ix_journal_entries_exit_at'), 'journal_entries', ['exit_at'], unique=False)
    op.create_index(op.f('ix_journal_entries_option_symbol'), 'journal_entries', ['option_symbol'], unique=False)
    op.create_index(op.f('ix_journal_entries_symbol'), 'journal_entries', ['symbol'], unique=False)
    op.create_table('positions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agent_name', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('option_symbol', sa.String(), nullable=False),
    sa.Column('contract_type', sa.String(), nullable=False),
    sa.Column('strike', sa.Float(), nullable=False),
    sa.Column('expiration', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('current_price', sa.Float(), nullable=True),
    sa.Column('premium_collected', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('opened_at', sa.DateTime(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('pnl', sa.Float(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_positions_agent_name'), 'positions', ['agent_name'], unique=False)
    op.create_index(op.f('ix_positions_opened_at'), 'positions', ['opened_at'], unique=False)
    op.create_index(op.f('ix_positions_option_symbol'), 'positions', ['option_symbol'], unique=True)
    op.create_index(op.f('ix_positions_status'), 'positions', ['status'], unique=False)
    op.create_index(op.f('ix_positions_symbol'), 'positions', ['symbol'], unique=False)
    op.create_table('scanner_opportunities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('iv_rank', sa.Float(), nullable=True),
    sa.Column('momentum_30d', sa.Float(), nullable=True),
    sa.Column('distance_from_20ma', sa.Float(), nullable=True),
    sa.Column('distance_from_50ma', sa.Float(), nullable=True),
    sa.Column('options_liquidity_score', sa.Float(), nullable=True),
    sa.Column('near_support', sa.Boolean(), nullable=False),
    sa.Column('composite_score', sa.Float(), nullable=False),
    sa.Column('scanned_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scanner_opportunities_composite_score'), 'scanner_opportunities', ['composite_score'], unique=False)
    op.create_index(op.f('ix_scanner_opportunities_scanned_at'), 'scanner_opportunities', ['scanned_at'], unique=False)
    op.create_index(op.f('ix_scanner_opportunities_symbol'), 'scanner_opportunities', ['symbol'], unique=False)
    op.create_table('trades',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agent_name', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('option_symbol', sa.String(), nullable=True),
    sa.Column('trade_type', sa.String(), nullable=False),
    sa.Column('side', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('premium', sa.Float(), nullable=True),
    sa.Column('strike', sa.Float(), nullable=True),
    sa.Column('expiration', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('pnl', sa.Float(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trades_agent_name'), 'trades', ['agent_name'], unique=False)
    op.create_index(op.f('ix_trades_symbol'), 'trades', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trades_symbol'), table_name='trades')
    op.drop_index(op.f('ix_trades_agent_name'), table_name='trades')
    op.drop_table('trades')
    op.drop_index(op.f('ix_scanner_opportunities_symbol'), table_name='scanner_opportunities')
    op.drop_index(op.f('ix_scanner_opportunities_scanned_at'), table_name='scanner_opportunities')
    op.drop_index(op.f('ix_scanner_opportunities_composite_score'), table_name='scanner_opportunities')
    op.drop_table('scanner_opportunities')
    op.drop_index(op.f('ix_positions_symbol'), table_name='positions')
    op.drop_index(op.f('ix_positions_status'), table_name='positions')
    op.drop_index(op.f('ix_positions_option_symbol'), table_name='positions')
    op.drop_index(op.f('ix_positions_opened_at'), table_name='positions')
    op.drop_index(op.f('ix_positions_agent_name'), table_name='positions')
    op.drop_table('positions')
    op.drop_index(op.f('ix_journal_entries_symbol'), table_name='journal_entries')
    op.drop_index(op.f('ix_journal_entries_option_symbol'), table_name='journal_entries')
    op.drop_index(op.f('ix_journal_entries_exit_at'), table_name='journal_entries')
    op.drop_index(op.f('ix_journal_entries_entry_at'), table_name='journal_entries')
    op.drop_index(op.f('ix_journal_entries_agent_name'), table_name='journal_entries')
    op.drop_table('journal_entries')
    op.drop_index(op.f('ix_agent_performance_date'), table_name='agent_performance')
    op.drop_index(op.f('ix_agent_performance_agent_name'), table_name='agent_performance')
    op.drop_table('agent_performance')
    # ### end Alembic commands ###
