"""
Proposals Routes — Human-in-the-loop trade approval layer.

Proposals are generated by the Lead Agent and must be explicitly approved
by the user before any order is submitted. auto_approve is always False
by default — the user must opt in explicitly.
"""
from datetime import datetime
from typing import Optional
from uuid import uuid4

from fastapi import APIRouter, Request, HTTPException
from pydantic import BaseModel
from sqlalchemy import select

from api.state import AppState
from core.database import AsyncSessionLocal
from models.proposal import TradeProposal

router = APIRouter()


def _get_state(request: Request) -> AppState:
    return request.app.state.app


def _proposal_to_dict(p: TradeProposal) -> dict:
    return {
        "id": p.id,
        "batch_id": p.batch_id,
        "status": p.status,
        "agent_name": p.agent_name,
        "symbol": p.symbol,
        "asset_type": p.asset_type,
        "contract_type": p.contract_type,
        "option_symbol": p.option_symbol,
        "strike": p.strike,
        "expiration": p.expiration,
        "delta": p.delta,
        "dte": p.dte,
        "bid": p.bid,
        "ask": p.ask,
        "mid_price": p.mid_price,
        "premium_per_contract": p.premium_per_contract,
        "contracts": p.contracts,
        "total_premium": p.total_premium,
        "collateral_required": p.collateral_required,
        "annualized_return": p.annualized_return,
        "probability_of_profit": p.probability_of_profit,
        "max_risk": p.max_risk,
        "distance_otm_pct": p.distance_otm_pct,
        "iv_rank": p.iv_rank,
        "scanner_score": p.scanner_score,
        "rationale": p.rationale,
        "created_at": p.created_at.isoformat() if p.created_at else None,
        "approved_at": p.approved_at.isoformat() if p.approved_at else None,
        "executed_at": p.executed_at.isoformat() if p.executed_at else None,
        "rejected_at": p.rejected_at.isoformat() if p.rejected_at else None,
    }


# ── QUERY ENDPOINTS ─────────────────────────────────────────────────


@router.get("/pending")
async def get_pending_proposals(request: Request, batch_id: Optional[str] = None):
    """Return all pending proposals, optionally filtered by batch_id."""
    state = _get_state(request)
    if not state.lead_agent:
        raise HTTPException(status_code=503, detail="Lead agent not initialized")
    proposals = await state.lead_agent.get_pending_proposals(batch_id=batch_id)
    return [_proposal_to_dict(p) for p in proposals]


@router.get("/history")
async def get_proposal_history(
    request: Request,
    limit: int = 50,
    offset: int = 0,
):
    """Return past proposals (approved, rejected, executed, expired) with pagination."""
    async with AsyncSessionLocal() as db:
        q = (
            select(TradeProposal)
            .where(TradeProposal.status.in_(["approved", "rejected", "executed", "expired"]))
            .order_by(TradeProposal.created_at.desc())
            .limit(limit)
            .offset(offset)
        )
        result = await db.execute(q)
        proposals = list(result.scalars().all())
    return [_proposal_to_dict(p) for p in proposals]


@router.get("/batch/{batch_id}")
async def get_batch_proposals(batch_id: str):
    """Return all proposals in a batch (any status)."""
    async with AsyncSessionLocal() as db:
        result = await db.execute(
            select(TradeProposal)
            .where(TradeProposal.batch_id == batch_id)
            .order_by(TradeProposal.created_at.asc())
        )
        proposals = list(result.scalars().all())
    return [_proposal_to_dict(p) for p in proposals]


# ── GENERATION ──────────────────────────────────────────────────────


@router.post("/generate")
async def generate_proposals(request: Request):
    """
    Trigger the Lead Agent to generate a new round of proposals.

    Runs the assignment logic against the latest Scanner data and fetches
    optimal contracts for each assignment. Proposals are saved as "pending"
    and returned for user review. Nothing is executed.
    """
    state = _get_state(request)
    if not state.lead_agent:
        raise HTTPException(status_code=503, detail="Lead agent not initialized")

    batch_id = str(uuid4())
    try:
        proposals = await state.lead_agent.generate_proposals(batch_id=batch_id)
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Proposal generation failed: {e}")

    return {
        "batch_id": batch_id,
        "count": len(proposals),
        "proposals": [_proposal_to_dict(p) for p in proposals],
    }


# ── SINGLE PROPOSAL ACTIONS ─────────────────────────────────────────


@router.post("/{proposal_id}/approve")
async def approve_proposal(proposal_id: int, request: Request):
    """Approve a single proposal and dispatch to the appropriate worker."""
    state = _get_state(request)
    if not state.lead_agent:
        raise HTTPException(status_code=503, detail="Lead agent not initialized")
    try:
        proposal = await state.lead_agent.approve_proposal(proposal_id)
    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e))
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Execution failed: {e}")
    return _proposal_to_dict(proposal)


@router.post("/{proposal_id}/reject")
async def reject_proposal(proposal_id: int, request: Request):
    """Reject a single proposal."""
    state = _get_state(request)
    if not state.lead_agent:
        raise HTTPException(status_code=503, detail="Lead agent not initialized")
    try:
        proposal = await state.lead_agent.reject_proposal(proposal_id)
    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e))
    return _proposal_to_dict(proposal)


class ModifyBody(BaseModel):
    strike: Optional[float] = None
    delta: Optional[float] = None
    contracts: Optional[int] = None


@router.post("/{proposal_id}/modify")
async def modify_proposal(proposal_id: int, body: ModifyBody, request: Request):
    """Modify a pending proposal (strike, delta, or contracts) and recalculate fields."""
    state = _get_state(request)
    if not state.lead_agent:
        raise HTTPException(status_code=503, detail="Lead agent not initialized")
    overrides = body.model_dump(exclude_none=True)
    if not overrides:
        raise HTTPException(status_code=400, detail="No modifications provided")
    try:
        proposal = await state.lead_agent.modify_proposal(proposal_id, overrides)
    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e))
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Modification failed: {e}")
    return _proposal_to_dict(proposal)


# ── BATCH ACTIONS ───────────────────────────────────────────────────


@router.post("/batch/{batch_id}/approve")
async def approve_batch(batch_id: str, request: Request):
    """Approve all pending proposals in a batch."""
    state = _get_state(request)
    if not state.lead_agent:
        raise HTTPException(status_code=503, detail="Lead agent not initialized")
    try:
        proposals = await state.lead_agent.approve_batch(batch_id)
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))
    return [_proposal_to_dict(p) for p in proposals]


@router.post("/batch/{batch_id}/reject")
async def reject_batch(batch_id: str, request: Request):
    """Reject all pending proposals in a batch."""
    state = _get_state(request)
    if not state.lead_agent:
        raise HTTPException(status_code=503, detail="Lead agent not initialized")
    try:
        proposals = await state.lead_agent.reject_batch(batch_id)
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))
    return [_proposal_to_dict(p) for p in proposals]
