"""Trade Proposal Model — Human-in-the-loop trade approval layer."""
from sqlalchemy import Column, Integer, String, Float, DateTime
from sqlalchemy.sql import func
from datetime import datetime

from models import Base


class TradeProposal(Base):
    """
    A proposed trade generated by the Lead Agent, awaiting user approval.

    Proposals are created in "pending" state. Users can approve, reject, or
    modify them via the Trade Desk. Only approved proposals are sent to workers
    for execution. auto_approve=True skips this flow (opt-in only).
    """

    __tablename__ = "proposals"

    id = Column(Integer, primary_key=True, autoincrement=True)

    # Grouping — all proposals from one Lead Agent cycle share a batch_id
    batch_id = Column(String, nullable=False, index=True)

    # Lifecycle — pending → approved/rejected → executed/expired
    status = Column(String, nullable=False, default="pending", index=True)

    # Which agent would execute this trade
    agent_name = Column(String, nullable=False)  # Covered-Calls | Cash-Secured-Puts | Wheel

    # Underlying
    symbol = Column(String, nullable=False)
    asset_type = Column(String, nullable=False)  # stock | etf

    # Contract details
    contract_type = Column(String, nullable=False)  # call | put
    option_symbol = Column(String, nullable=True)  # OCC symbol, e.g. AAPL240119C00185000
    strike = Column(Float, nullable=False)
    expiration = Column(String, nullable=False)  # YYYY-MM-DD
    delta = Column(Float, nullable=False)
    dte = Column(Integer, nullable=False)

    # Pricing
    bid = Column(Float, nullable=False)
    ask = Column(Float, nullable=False)
    mid_price = Column(Float, nullable=False)

    # Economics
    premium_per_contract = Column(Float, nullable=False)  # mid * 100
    contracts = Column(Integer, nullable=False, default=1)
    total_premium = Column(Float, nullable=False)  # premium_per_contract * contracts
    collateral_required = Column(Float, nullable=False)  # strike*100*contracts for puts; 0 for covered calls
    annualized_return = Column(Float, nullable=False)  # % annualized on collateral
    probability_of_profit = Column(Float, nullable=False)  # 1 - abs(delta) as %

    # Risk
    max_risk = Column(Float, nullable=False)  # worst-case dollar loss
    distance_otm_pct = Column(Float, nullable=False)  # % OTM from current price

    # Context
    iv_rank = Column(Float, nullable=False)
    scanner_score = Column(Float, nullable=True)

    # Human-readable explanation
    rationale = Column(String, nullable=False)

    # Capital awareness — populated at proposal generation time
    pct_of_buying_power = Column(Float, nullable=True)  # % of buying power this trade uses
    cumulative_pct = Column(Float, nullable=True)  # running % if all prior proposals approved

    # Timestamps
    created_at = Column(DateTime, nullable=False, server_default=func.now())
    approved_at = Column(DateTime, nullable=True)
    executed_at = Column(DateTime, nullable=True)
    rejected_at = Column(DateTime, nullable=True)
